### ISSUE TITLE
[BE-224] bug: 이메일 주소 환경변수에 의한 로컬 실행 및 테스트 에러 수정

### ISSUE THREAD

**Issue by Profile-exe** [JNU-Parking-Ticket-Project/Parking-Ticket-BE#470]
## 버그설명

- 이메일 환경변수가 `dev`, `prod`에만 적용되어 로컬, 테스트 환경에서 로컬환경 실행 및 테스트가 깨지는 문제 발생
- `profile`을 구분하지 않고 해당 속성을 통일해 관리하도록 변경할 예정

### AS-IS
```yaml
---
spring:
  config:
    activate:
      on-profile: dev
mail:
  passwd-url: ${PASSWD-URL:https://jnu-parking.econovation.kr/password-reset/}
  announcement-url: ${ANNOUNCEMENT_URL:https://jnu-parking.econovation.kr/announcement/}
---
spring:
  config:
    activate:
      on-profile: prod
mail:
  passwd-url: ${PASSWD-URL:https://apply.jnu-parking.com/password-reset/}
  announcement-url: ${ANNOUNCEMENT_URL:https://apply.jnu-parking.com/announcement/}

```

### TO-BE
```yaml

# activate on-profile 제거

mail:
  passwd-url: ${PASSWD_URL:https://apply.jnu-parking.com/password-reset/}
  announcement-url: ${ANNOUNCEMENT_URL:https://apply.jnu-parking.com/announcement/}
```

<br/>

## 체크리스트

- [x] `assignee` 설정 (선택)
- [x] `labels` 설정
- [ ] `milestone` 설정
- [ ] production DB Schema 반영

<br/>

## 주의사항
